USE PRACTICE;
CREATE TABLE IF NOT EXISTS  UNIFORM (UCode int PRIMARY KEY, UName varchar(20),Color VARCHAR(10));
CREATE TABLE IF NOT EXISTS COST(UCode int, Size VARCHAR(10), Price float, PRIMARY KEY(UCode, Size));
INSERT INTO UNIFORM(UCode, UName, Color) VALUES (101,'Handekerchief','Red');
INSERT INTO UNIFORM(UCode, UName, Color) VALUES (7,'Shirt','White');
ALTER TABLE Cost ADD FOREIGN KEY (UCode) REFERENCES Uniform(UCode);
INSERT INTO COST (UCode,Size,Price) VALUES (7,'M',100);
ALTER TABLE UNIFORM MODIFY UNAME VARCHAR(20) NOT NULL;
ALTER TABLE COST MODIFY Price float CHECK(Price>0);