create DATABASE IF NOT EXISTS SPORTS;
use SPORTS;
CREATE TABLE IF NOT EXISTS team (TeamID INT UNIQUE, TeamName VARCHAR(20));
ALTER TABLE Team ADD CONSTRAINT PRIMARY KEY(TeamID);
ALTER TABLE Team MODIFY TableName VARCHAR(20);
DESC Team;
INSERT INTO team (TeamID, TableName)
VALUES
(1,'Team Titan'),
(2,'Team Rockers'),
(3,'Team Magnet'),
(4,'Team Hurricane');
SELECT * FROM Team;
CREATE TABLE IF NOT EXISTS Match_Details (MatchID CHAR(2), MatchDate Date, FirstTeamID int, SecondTeamID int, FirstTeamScore int, SecondTeamScore int);
ALTER TABLE MATCH_DETAILS CHANGE MATCH_ID MATCHID CHAR(2);
INSERT INTO Match_Details (MatchID, MatchDate, FirstTeamID, SecondTeamID, FirstTeamScore, SecondTeamScore)
VALUES
('M1','2018-07-17',1,2,90,86),
('M2','2018-07-18',3,4,45,48),
('M3','2018-07-19',1,3,78,56),
('M4','2018-07-19',2,4,56,67),
('M5','2018-07-18',1,4,32,87),
('M6','2018-07-17',2,3,67,51);
SELECT MATCHID FROM  MATCH_DETAILS WHERE FIRSTTEAMSCORE>70 AND SECONDTEAMSCORE>70;
SELECT MATCHID FROM  MATCH_DETAILS WHERE FIRSTTEAMSCORE<70 AND SECONDTEAMSCORE>70;

SELECT MATCH_DETAILS.MATCHID, MATCH_DETAILS.MATCHDATE 
FROM MATCH_DETAILS
WHERE (FIRSTTEAMID = 1 AND FIRSTTEAMSCORE > SECONDTEAMSCORE)
OR (SECONDTEAMID = 1 AND SECONDTEAMSCORE > FIRSTTEAMSCORE);

SELECT MATCH_DETAILS.MATCHID, MATCH_DETAILS.MATCHDATE 
FROM MATCH_DETAILS
WHERE (FIRSTTEAMID = 2 AND FIRSTTEAMSCORE > SECONDTEAMSCORE)
OR (SECONDTEAMID = 2 AND SECONDTEAMSCORE > FIRSTTEAMSCORE);

SELECT * FROM T_DATA;

ALTER TABLE TEAM RENAME TO T_DATA;
ALTER TABLE T_Data CHANGE COLUMN TeamID T_ID INT UNIQUE;
ALTER TABLE T_Data CHANGE COLUMN TeamName T_NAME VARCHAR(20);

